# Generated by Django 5.0.1 on 2024-01-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_nbr',
            field=models.IntegerField(unique=True),
        ),
    ]
