# Generated by Django 5.0.1 on 2024-01-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_room_nbr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_nbr',
            field=models.CharField(unique=True),
        ),
    ]
