# Generated by Django 5.0.1 on 2024-01-11 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceilings', '0002_remove_ceiling_rooms'),
        ('floorFinishes', '0003_remove_floorfinish_rooms'),
        ('roomTypes', '0014_alter_roomtype_ffes'),
        ('rooms', '0007_remove_room_room_nbr'),
        ('wallFinishes', '0002_remove_wallfinish_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='ceilings',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='ceilings.ceiling'),
        ),
        migrations.AddField(
            model_name='room',
            name='floorFinishes',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='floorFinishes.floorfinish'),
        ),
        migrations.AddField(
            model_name='room',
            name='roomType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='roomTypes.roomtype'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_nbr',
            field=models.CharField(default=1, ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='wallFinishes',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='wallFinishes.wallfinish'),
        ),
    ]
