# Generated by Django 5.0.1 on 2024-01-16 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_room_ceilings_room_floorfinishes_room_roomtype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='ceilings',
        ),
        migrations.RemoveField(
            model_name='room',
            name='floorFinishes',
        ),
        migrations.RemoveField(
            model_name='room',
            name='wallFinishes',
        ),
    ]
