# Generated by Django 5.0.1 on 2024-01-11 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floorFinishes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='floorfinish',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_floors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='floorfinish',
            name='spec_code',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='floorfinish',
            name='spec_code_suffix',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='floorfinish',
            name='spec_title',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
