# Generated by Django 5.0.1 on 2024-01-11 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floorFinishes', '0002_floorfinish_owner_floorfinish_spec_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floorfinish',
            name='rooms',
        ),
    ]
