# Generated by Django 5.0.1 on 2024-01-17 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floorFinishes', '0003_remove_floorfinish_rooms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floorfinish',
            old_name='spec_code_suffix',
            new_name='spec_name',
        ),
        migrations.RemoveField(
            model_name='floorfinish',
            name='spec_title',
        ),
    ]
