# Generated by Django 5.0.1 on 2024-01-09 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('floorFinishes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_code', models.CharField(max_length=2000)),
                ('spec_code_suffix', models.CharField()),
                ('spec_title', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('floor_finish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='floorFinishes.floorfinish')),
            ],
        ),
    ]
