# Generated by Django 5.0.1 on 2024-01-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ffe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ffe_code', models.CharField(max_length=10, unique=True)),
                ('ffe_name', models.CharField()),
                ('ffe_group', models.CharField(max_length=1)),
            ],
        ),
    ]
