# Generated by Django 5.0.1 on 2024-01-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffes', '0002_ffe_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='ffe',
            name='ffe_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
