# Generated by Django 5.0.1 on 2024-01-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffes', '0003_ffe_ffe_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ffe',
            name='ffe_code',
            field=models.CharField(max_length=10),
        ),
    ]
