# Generated by Django 5.0.1 on 2024-01-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffes', '0005_remove_ffe_ffe_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ffe',
            name='ffe_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
