# Generated by Django 5.0.1 on 2024-01-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffes', '0001_initial'),
        ('roomTypes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='ffes',
            field=models.ManyToManyField(related_name='roomTypes', to='ffes.ffe'),
        ),
    ]
