# Generated by Django 5.0.1 on 2024-01-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomTypes', '0002_roomtype_ffes'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='room_nbr',
            field=models.ManyToManyField(related_name='roomTypes', to='rooms.room'),
        ),
    ]
