# Generated by Django 5.0.1 on 2024-01-09 19:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomTypes', '0003_roomtype_room_nbr'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='room_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
