# Generated by Django 5.0.1 on 2024-01-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffes', '0001_initial'),
        ('roomTypes', '0004_roomtype_room_img'),
        ('rooms', '0003_alter_room_room_nbr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='area',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='ffes',
            field=models.ManyToManyField(blank=True, related_name='roomTypes', to='ffes.ffe'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='height',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='room_img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='room_nbr',
            field=models.ManyToManyField(blank=True, related_name='roomTypes', to='rooms.room'),
        ),
    ]
