# Generated by Django 5.0.1 on 2024-01-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffes', '0002_ffe_owner'),
        ('roomTypes', '0006_roomtype_owner'),
        ('rooms', '0003_alter_room_room_nbr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='ffes',
            field=models.ManyToManyField(blank=True, null=True, related_name='roomTypes', to='ffes.ffe'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='room_nbr',
            field=models.ManyToManyField(blank=True, null=True, related_name='roomTypes', to='rooms.room'),
        ),
    ]
