# Generated by Django 5.0.1 on 2024-01-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffes', '0002_ffe_owner'),
        ('roomTypes', '0009_remove_roomtype_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='ffes',
            field=models.ManyToManyField(blank=True, related_name='roomTypes', to='ffes.ffe'),
        ),
    ]
