# Generated by Django 5.0.1 on 2024-01-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffes', '0002_ffe_owner'),
        ('roomTypes', '0010_alter_roomtype_ffes'),
        ('rooms', '0004_room_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='rooms',
            field=models.ManyToManyField(blank=True, null=True, related_name='roomTypes', to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='ffes',
            field=models.ManyToManyField(blank=True, null=True, related_name='roomTypes', to='ffes.ffe'),
        ),
    ]
