# Generated by Django 5.0.1 on 2024-01-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffes', '0003_ffe_ffe_img'),
        ('roomTypes', '0013_remove_roomtype_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='ffes',
            field=models.ManyToManyField(blank=True, related_name='roomTypes', to='ffes.ffe'),
        ),
    ]
