# Generated by Django 5.0.1 on 2024-01-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomTypes', '0014_alter_roomtype_ffes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='room_code',
            field=models.CharField(max_length=10),
        ),
    ]
