# Generated by Django 5.0.1 on 2024-01-16 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomTypes', '0016_alter_roomtype_room_img'),
        ('rooms', '0008_room_ceilings_room_floorfinishes_room_roomtype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='ffes',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='room_nbrs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roomTypes', to='rooms.room'),
        ),
    ]
