# Generated by Django 5.0.1 on 2024-01-16 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomTypes', '0017_remove_roomtype_ffes_roomtype_room_nbrs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='room_nbrs',
        ),
    ]
