# Generated by Django 5.0.1 on 2024-01-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffes', '0005_remove_ffe_ffe_img'),
        ('roomTypes', '0018_remove_roomtype_room_nbrs'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='ffes',
            field=models.ManyToManyField(blank=True, related_name='roomTypes', to='ffes.ffe'),
        ),
    ]
