# Generated by Django 5.0.1 on 2024-01-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceilings', '0003_alter_ceiling_spec_code_and_more'),
        ('floorFinishes', '0003_remove_floorfinish_rooms'),
        ('roomTypes', '0019_roomtype_ffes'),
        ('wallFinishes', '0003_alter_wallfinish_spec_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='ceilings',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='ceilings.ceiling'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='floorFinishes',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='floorFinishes.floorfinish'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='wallFinishes',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='wallFinishes.wallfinish'),
        ),
    ]
