# Generated by Django 5.0.1 on 2024-01-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomTypes', '0020_roomtype_ceilings_roomtype_floorfinishes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='room_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
