# Generated by Django 5.0.1 on 2024-01-17 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceilings', '0003_alter_ceiling_spec_code_and_more'),
        ('floorFinishes', '0004_rename_spec_code_suffix_floorfinish_spec_name_and_more'),
        ('roomTypes', '0022_alter_roomtype_room_code'),
        ('wallFinishes', '0003_alter_wallfinish_spec_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='ceilings',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='floorFinishes',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='wallFinishes',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='ceilings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='ceilings.ceiling'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='floorFinishes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='floorFinishes.floorfinish'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='wallFinishes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='wallFinishes.wallfinish'),
        ),
    ]
