# Generated by Django 5.0.1 on 2024-01-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomTypes', '0023_remove_roomtype_ceilings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='room_code',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='room_img',
            field=models.CharField(blank=True, default='https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='room_name',
            field=models.CharField(max_length=255),
        ),
    ]
