# Generated by Django 5.0.1 on 2024-01-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomTypes', '0024_alter_roomtype_room_code_alter_roomtype_room_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='room_img',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
