# Generated by Django 5.0.1 on 2024-01-11 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roomTypes', '0012_alter_roomtype_area_alter_roomtype_height_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bldg_code', models.CharField(max_length=10, unique=True)),
                ('bldg_name', models.CharField()),
                ('bldg_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_buildings', to=settings.AUTH_USER_MODEL)),
                ('roomTypes', models.ManyToManyField(blank=True, null=True, related_name='buildings', to='roomTypes.roomtype')),
            ],
        ),
    ]
