# Generated by Django 5.0.1 on 2024-01-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
        ('roomTypes', '0013_remove_roomtype_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='roomTypes',
            field=models.ManyToManyField(blank=True, related_name='buildings', to='roomTypes.roomtype'),
        ),
    ]
