# Generated by Django 5.0.1 on 2024-01-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_alter_building_bldg_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='bldg_img',
            field=models.CharField(blank=True, null=True),
        ),
    ]
