# Generated by Django 5.0.1 on 2024-01-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0004_alter_building_bldg_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='bldg_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
