# Generated by Django 5.0.1 on 2024-01-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0005_building_bldg_description'),
        ('roomTypes', '0021_alter_roomtype_room_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='roomTypes',
            field=models.ManyToManyField(blank=True, null=True, related_name='buildings', to='roomTypes.roomtype'),
        ),
    ]
