# Generated by Django 5.0.1 on 2024-01-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HBN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hbn_code', models.CharField(max_length=20)),
                ('hbn_name', models.CharField(max_length=255)),
                ('hbn_link', models.CharField(blank=True, max_length=2000, null=True)),
                ('hbn_img', models.CharField(blank=True, max_length=2000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
